# Generated by Django 4.2.6 on 2024-01-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_hashtag',
            field=models.ManyToManyField(null=True, to='socialnetworks.hashtag'),
        ),
    ]
