# Generated by Django 4.2.6 on 2024-01-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0002_alter_post_image_alter_post_post_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_hashtag',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='post_hashtag',
            field=models.ManyToManyField(null=True, to='socialnetworks.post'),
        ),
    ]
