# Generated by Django 4.2.6 on 2023-12-20 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0002_reporttype_content_alter_auction_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='use_care',
            field=models.ManyToManyField(related_query_name='auction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_query_name='product', to='socialnetworks.category'),
        ),
    ]
