# Generated by Django 4.2.6 on 2023-12-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0003_auction_use_care_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participateauction',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='participateauction', to='socialnetworks.auction'),
        ),
    ]
