# Generated by Django 4.2.6 on 2024-01-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0004_remove_hashtag_post_hashtag_post_post_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
