# Generated by Django 4.2.6 on 2023-12-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0004_alter_participateauction_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='use_care',
            new_name='user_care',
        ),
    ]
