# Generated by Django 4.2.6 on 2024-01-11 09:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0007_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liketype',
            name='icon',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='icon'),
        ),
    ]
