# Generated by Django 4.2.6 on 2024-01-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0008_alter_liketype_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liketype',
            name='icon',
        ),
    ]
