# Generated by Django 4.2.6 on 2024-01-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0009_remove_liketype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialnetworks.liketype'),
        ),
    ]
