# Generated by Django 4.2.6 on 2024-01-14 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0012_alter_comments_post_alter_images_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='user_care',
            field=models.ManyToManyField(null=True, related_query_name='auction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='notice', to='socialnetworks.post'),
        ),
    ]
