# Generated by Django 4.2.6 on 2024-01-14 10:07

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0013_alter_auction_buyer_alter_auction_user_care_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_query_name='auction', to='socialnetworks.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
