# Generated by Django 4.2.6 on 2024-01-18 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0015_alter_auction_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reason',
        ),
        migrations.AlterField(
            model_name='report',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialnetworks.auction'),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialnetworks.post'),
        ),
    ]
