# Generated by Django 4.2.6 on 2024-01-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0018_alter_post_user_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='socialnetworks.follow'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='notice', to='socialnetworks.post'),
        ),
    ]
