# Generated by Django 4.2.6 on 2024-01-28 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0021_remove_notice_follow_remove_notice_post_notice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='notice', to='socialnetworks.post'),
        ),
        migrations.AddField(
            model_name='notice',
            name='user_notice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='user_care',
            field=models.ManyToManyField(blank=True, related_query_name='auction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_notice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_hashtag',
            field=models.ManyToManyField(blank=True, related_query_name='hashtag', to='socialnetworks.hashtag'),
        ),
    ]
